### ISSUE TITLE
improve opx-config-route and opx-config-vrf to give proper return value to inform user what is missing when the crash happens

### ISSUE THREAD

**Issue by Tejaswi-Goel** [open-switch/opx-tools#12]

**Comment by Tejaswi-Goel** [comment]
**Example Case 1:**
root@OPX:/home/admin# opx-config-route create --vrf_name red --dst 192.168.10.0/24 --nh 192.168.50.1
args: {'nh': '192.168.50.1', 'vrf_name': 'red', 'dst': '192.168.10.0/24', 'command': 'create'}
version is: ipv4
base-route/obj/entry
Traceback (most recent call last):
File "/usr/bin/opx-config-route", line 103, in <module>
nas_route_op("create", cps_obj, version)
File "/usr/bin/opx-config-route", line 74, in nas_route_op
nas_ut.get_cb_method(op)(obj)
File "/usr/lib/x86_64-linux-gnu/opx/nas_ut_framework.py", line 44, in create
ret = commit(obj, "create")
File "/usr/lib/x86_64-linux-gnu/opx/nas_ut_framework.py", line 35, in commit
rs = ret_obj.get_attr_data('cps/object-group/return-string')
File "/usr/lib/opx/cps_object.py", line 338, in get_attr_data
raise ValueError("Could not find attribute '" + attr + "' in the CPS object")
ValueError: Could not find attribute 'cps/object-group/return-string' in the CPS object
**Adding code to verify if the given VRF exists with ports in it to be able to inform user what is missing.**

**2: Add code to enable static route leaking between VRFs.**

**Comment by Tejaswi-Goel** [comment]
PR raised: #15
